### ISSUE TITLE
Display country name instead of country code

### ISSUE THREAD

**Issue by fdmarcin** [fdmarcin/whereiss#1]
Maybe add a file with name-code pairs, and have the script check against it.

**Comment by yoavtzelnick** [comment]
Please allow branch creation permissions. I can't seem to push a new branch.

**Comment by fdmarcin** [comment]
Closed by #2

**Comment by fdmarcin** [comment]
@yoavtzelnick Hey, I see you managed with forking. I think it's a cleaner way for the repo, and I should've included it in a "Contributing" bit in the README. Thanks again :)
